apiVersion: v1
kind: Service
metadata:
  name: lula-runner
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.runner.service.type }}
  ports:
    - port: {{ .Values.runner.service.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: lula-runner
