apiVersion: v1
kind: Secret
metadata:
  name: lula-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  LG_REMOTE_API_BEARER_TOKEN: {{ .Values.secrets.remoteApiBearerToken | quote }}
  LG_RUNNER_API_KEY: {{ .Values.secrets.runnerApiKey | quote }}
  DIGITAL_OCEAN_MODEL_ACCESS_KEY: {{ .Values.secrets.digitalOceanModelAccessKey | quote }}
  LG_CHECKPOINT_REDIS_URL: {{ .Values.secrets.checkpointRedisUrl | quote }}
  LG_CHECKPOINT_POSTGRES_DSN: {{ .Values.secrets.checkpointPostgresDsn | quote }}
  LG_AUTH_HMAC_SECRET: {{ .Values.secrets.hmacSecret | quote }}
