apiVersion: v1
kind: Service
metadata:
  name: lula-orch
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "{{ .Values.orchestrator.service.port }}"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
spec:
  type: {{ .Values.orchestrator.service.type }}
  ports:
    - port: {{ .Values.orchestrator.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: lula-orch
