apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lula-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lula-secret-store
    kind: SecretStore
  target:
    name: lula-secrets
    creationPolicy: Owner
  data:
    - secretKey: LG_RUNNER_APPROVAL_SECRET
      remoteRef:
        key: lula/approval-secret
    - secretKey: LG_JWT_SECRET
      remoteRef:
        key: lula/jwt-secret
    - secretKey: LG_OPENAI_API_KEY
      remoteRef:
        key: lula/openai-api-key
    - secretKey: LG_ANTHROPIC_API_KEY
      remoteRef:
        key: lula/anthropic-api-key
